version: '3.7'

services:
  php-service:
    environment:
      - APP_ENV=dev
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/app/
    ports:
      - "2000:9000"
    entrypoint: ["/bin/sh", "-c", "composer install && php-fpm"]
  nginx-service:
    environment:
      - APP_ENV=dev
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./app:/app/
    ports:
      - "6001:80"